#Program for Demonstarting the Fun of Arithmetic Operators
#Arithmetic OperatorsEx1.py
a=float(input("Enter Val of a:"))
b=float(input("Enter Val of b:"))
print("*"*50)
print("\tRESULTS OF ARITHMETIC OPERATORS")
print("*"*50)
print("\t\tsum({},{})={}".format(a,b,a+b))
print("\t\tsub({},{})={}".format(a,b,a-b))
print("\t\tmul({},{})={}".format(a,b,a*b))
print("\t\tDiv({},{})={}".format(a,b,a/b))
print("\t\tFloorDiv({},{})={}".format(a,b,a//b))
print("\t\tModDiv({},{})={}".format(a,b,a%b))
print("\t\tPow({},{})={}".format(a,b,a**b))
print("*"*50)