#EmpPaySlip.py
eno=int(input("Enter Employee Number:"))
name=input("Enter Employee Name:")
basicsal=float(input("Enter Employee Basic Salary:"))
if(basicsal<=0):
    print("{} Invalid Salary:".format(basicsal))
if(basicsal>=10000):
    da=basicsal*(20/100)
    ta=basicsal*(10/100)
    hra=basicsal*(7/100)
    cca=basicsal*(0.5/100)
    ma=basicsal*(0.25/100)
    lic=basicsal*(2/100)
    gpf=basicsal*(1/100)
if(0<basicsal<10000):
    da=basicsal*(15/100)
    ta=basicsal*(7.5/100)
    hra=basicsal*(5/100)
    cca=basicsal*(0.25/100)
    ma=basicsal*(0.12/100)
    lic=basicsal*(1.5/100)
    gpf=basicsal*(1/100)
if(basicsal>0): #Other Statements--display payslip
    netsal = (basicsal + ta + da + hra + cca + ma) - (lic + gpf)
    print("*" * 50)
    print("\tEMPLOYEE PAY SLIP")
    print("*" * 50)
    print("\tEmployee Number:{}".format(eno))
    print("\tEmployee Name:{}".format(name))
    print("\tEmployee Basic Salary:{}".format(basicsal))
    print("\t\tDA:{}".format(da))
    print("\t\tTA:{}".format(ta))
    print("\t\tHRA:{}".format(hra))
    print("\t\tCCA:{}".format(cca))
    print("\t\tMA:{}".format(ma))
    print("Deductions")
    print("\t\tLIC:{}".format(lic))
    print("\t\tgpf:{}".format(gpf))
    print("\tNET SALARY:{}".format(netsal))
    print("*" * 50)
